-- Generated by Prisma Migrate. Do not edit manually.
CREATE TABLE "Folder" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Folder_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "Bookmark" (
    "id" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "url" TEXT NOT NULL,
    "tags" TEXT[] NOT NULL,
    "folderId" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Bookmark_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "Folder_name_idx" ON "Folder"("name");
CREATE INDEX "Bookmark_folderId_idx" ON "Bookmark"("folderId");
CREATE INDEX "Bookmark_title_idx" ON "Bookmark"("title");
CREATE INDEX "Bookmark_createdAt_id_idx" ON "Bookmark"("createdAt", "id");

ALTER TABLE "Bookmark"
ADD CONSTRAINT "Bookmark_folderId_fkey"
FOREIGN KEY ("folderId") REFERENCES "Folder"("id") ON DELETE CASCADE ON UPDATE CASCADE;
